### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [jamesotto852/ggdensity#21]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that your package somehow includes references to ggplot2 code from when it was build, which causes the check to emit the "Import not declared from..." error. Please see https://www.tidyverse.org/blog/2022/09/playing-on-the-same-team-as-your-dependecy/ for some more info about why this can cause issues.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by jamesotto852** [comment]
This has been remedied in #22 by replacing all instances of `get("foo", asNamespace("ggplot2"))` with the relevant code (slightly modifed) from **ggplot2**. **ggdensity** is now passing with the release candidate of **ggplot2**, and we are in the process of submitting to CRAN.

***

@thomasp85 While these changes ensure **ggdensity** is passing checks w/ the release candidate of **ggplot2**, we've noticed that a recent change in the rc branch is breaking:
``` r
library("ggplot2")
library("ggdensity")

df <- data.frame(x = rnorm(1000), y = rnorm(1000))
p <- ggplot(df, aes(x, y)) + coord_equal()
p + geom_hdr()
#> Warning: Computation failed in `stat_hdr()`
#> Caused by error in `vec_size()`:
#> ! `x` must be a vector, not an environment.
```

![](https://i.imgur.com/n2xZA7R.png)

<sup>Created on 2022-10-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

***

I believe this was introduced with the introduction of `vec_rbind0() `in tidyverse/ggplot2@a9c316d. It looks like this is breaking just in the contex of **ggplot2**, with many other geoms failing with the same warning:

``` r
library("ggplot2")

df <- data.frame(x = rnorm(1000), y = rnorm(1000))
p <- ggplot(df, aes(x, y)) + coord_equal()
p + geom_density_2d()
#> Warning: Computation failed in `stat_density2d()`
#> Caused by error in `vec_size()`:
#> ! `x` must be a vector, not an environment.
#> Warning in min(x, na.rm = na.rm): no non-missing arguments to min; returning Inf
#> Warning in max(x, na.rm = na.rm): no non-missing arguments to max; returning
#> -Inf
#> Warning in max(f): no non-missing arguments to max; returning -Inf
#> Error in `geom_density_2d()`:
#> ! Problem while computing stat.
#> ℹ Error occurred in the 1st layer.
#> Caused by error in `seq_len()`:
#> ! argument must be coercible to non-negative integer
p + geom_smooth()
#> `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'
#> Warning: Computation failed in `stat_smooth()`
#> Caused by error in `vec_size()`:
#> ! `x` must be a vector, not an environment.
```

![](https://i.imgur.com/wkFCYGN.png)

<sup>Created on 2022-10-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I just wanted to make sure you were aware of the problem. If it would be helpful I can open an issue on **ggplot2** with this information.
