### ISSUE TITLE
Update package to the new `linewidth` aesthetic

### ISSUE THREAD

**Issue by eliocamp** [jamesotto852/ggdensity#23]
The latest ggplot2 update added the `linewidth` aesthetic to control well... line width instead of size. While the old `size` parameter still works (for now), it would be nice for the package not to throw warnings to the user. Here's a guide on how to update: https://www.tidyverse.org/blog/2022/08/ggplot2-3-4-0-size-to-linewidth/

Note: 

Hi! I was asked to review your paper for the R Journal. 

I think this is a great package with clear use cases and motivations. I cannot wait to find a reason to use it and blow all my colleagues minds :smile: . 

As part of the review, I'm looking at the code of the package and i thought that in the spirit of open source, it would be much more productive if I voiced some of my comments as issues. This would allow us to have a conversation to clear up any misunderstanding instead of you having to rely solely on my potentially confusing review comments. This is in the spirit of rOpenSci package peer review system, which I think it's great. The editor told me that it was fine that I do this, although it would compromise my anonymity. Well, consider it compromised, I guess 😁.

**Comment by jamesotto852** [comment]
Support for the linewidth aesthetic was added in #31.

``` r
library("ggdensity")
#> Loading required package: ggplot2

set.seed(1)
df <- data.frame(x = rnorm(1e4), y = rnorm(1e4))

ggplot(df, aes(x, y)) +
  geom_hdr_lines(linewidth = 3)
```

![](https://i.imgur.com/hRLvt9w.png)

<sup>Created on 2023-02-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
