### ISSUE TITLE
Align function names to ggplot2's conventions

### ISSUE THREAD

**Issue by eliocamp** [jamesotto852/ggdensity#24]
It might be too late for such a drastic change, but how about changing the names of the functions to follow more closely ggplot2's naming conventions?

For example, renaming `geom_hdr_lines()` to `geom_density_2d_hdr()` will make the function more discoverable through autocompletion (as the user can start typing `geom_density` and then get a list of the available density-related geometries). 

Same with `geom_hdr_rug()` to `geom_rug_hdr()` and `geom_hdr_point()` to `geom_point_hdr()`. (This will also solve the namespace conflict with  `gghdr::geom_hdr_rug()`.)

**Comment by jamesotto852** [comment]
While this naming scheme has advantages (e.g. discovery through autocomplete), it is our opinion that it would decrease the usability of **ggdensity**. The current naming scheme is memorable and predictable: each layer function begins with `geom/stat_hdr` and the use of suffixes like `_lines`, `_points`,  and `_fun` is always the same. The current naming scheme also works well with autocomplete, all of the exported layer functions are visible after typing "`geom_hdr`".

Further, we feel that such a drastic change would be disruptive to the current users of **ggdensity**.
