### ISSUE TITLE
Use `\dontrun{}` to skip examples

### ISSUE THREAD

**Issue by eliocamp** [jamesotto852/ggdensity#25]
A lot of the examples do not run on CRAN apparently for speed concerns. I think that the correct way to skip tests is to use `\dontrun{}` (see [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-R-documentation-files)) instead of commenting them out or using `if (FALSE)`.

**Comment by jamesotto852** [comment]
We have replaced commented out examples in the documentation with `\dontrun{}` in #31.
