### ISSUE TITLE
Remove duplicated code. 

### ISSUE THREAD

**Issue by eliocamp** [jamesotto852/ggdensity#29]
There is quite a bit of code duplication. For instance, the code to define the histogram mesh is copied 6 times (in hdr.R, hdr_lines.R and hdr_point.R, once for `method == "histogram"` and once for `method == "freqpoly"` in each file). The code to `switch()` between methods is also repeated 5 times.

These duplications will make it very hard to maintain the package and to add new density estimators. So I recommend refactoring the code. This includes 2 related recommendations:

1. Move the code that computes HDR into a single stat (or two: one for 1D and one for 2D, if needed). Then, each geom can represent that stat with different geometries. (This is more aligned with the difference between the statistical transformations and the geometries used to represent them).

2. Implement the stat to be agnostic towards which method is used to estimate the density and then implement the different density estimators separately. This might make it much easier for the developers to maintain and implement new methods as well as for users to use their own. (It's also related to #28).

   To illustrate how this might work, take the example of fitting an bivariate exponential distribution that's in the article. This looks like a natural extension of `method = "mvnorm"`, which fits a bivariate normal. This suggests that it could be desirable for the user to use their own methods to estimate the density distribution. So the bivariate exponential could be simplified to something along these lines:

    ``` r
    # define my own density estimation function
    biexp <- function(data) {
      # estimate parameters governing joint pdf
      lambda_hat <- apply(data, 2, mean)
    
      # output a density function
      function(x, y) dexp(x, lambda[1]) * dexp(y, lambda[2])
    }
    
    ggplot(df, aes(x, y)) +
      geom_hdr(method = biexp) +
      geom_point(fill = "lightgreen", shape = 21) +
      coord_fixed() +
      scale_x_continuous(limits = c(0, 7)) +
      scale_y_continuous(limits = c(0, 7))
    ```
 
   Most of the work for this change seems to be already done in the `fun_iso()` function. This would make `geom_hdr_fun()` redundant (less maintenance overhead and less code duplication) and potentially make it much easier to implement new methods.

**Comment by jamesotto852** [comment]
Much of the discussed duplication has been eliminated with the refactoring of statistical computations to `get_hdr()` and `get_hdr_1d()` (see #28).

We have further refactored the `ggproto` classes through the use of a new `$output` field, allowing for inheritance between **ggdensity**'s `$compute_group()` methods (in a way similar to `ggplot2::StatDensity2d$contour_type`).

We have also reworked the `method` argument to better facilitate the extension of **ggdensity**, it now accepts either a character vector or function call. We include a few examples below, for details see `vignette("method", package = "ggdensity")`

``` r
library("ggdensity")
#> Loading required package: ggplot2

set.seed(1)
df_normal <- data.frame(x = rnorm(1e3), y = rnorm(1e3))

ggplot(df_normal, aes(x, y)) +
  geom_hdr(method = "kde")
```

![](https://i.imgur.com/SoVx25K.png)

``` r

ggplot(df_normal, aes(x, y)) +
  geom_hdr(method = method_kde())
```

![](https://i.imgur.com/yGyZamn.png)

``` r

ggplot(df_normal, aes(x, y)) +
  geom_hdr(method = method_kde(adjust = .5))
```

![](https://i.imgur.com/SIcpcJL.png)

``` r


df_biexp <- data.frame(x = rexp(1e3), y = rexp(1e3))

method_biexp <- function() {

  function(data) {
    # estimate parameters governing joint pdf
    lambda_hat <- c(mean(data$x), mean(data$y))
  
    # output a density function
    function(x, y) dexp(x, lambda_hat[1]) * dexp(y, lambda_hat[2])
  }

}

ggplot(df_biexp, aes(x, y)) +
  geom_hdr(method = method_biexp())
```

![](https://i.imgur.com/sM3iHLp.png)

<sup>Created on 2023-02-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
