### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by eliocamp** [jamesotto852/ggdensity#30]
Currently there are no test in the package and many examples are not run. `covr::package_coverage()` reports 0.15% coverage. I think that adding tests to increase coverage to at least 60% is necessary before publication (ideally it should be higher, but testing ggplot2 extensions can be hard since it involves a lot of visual testing; even ggplot2 barely reaches 80%). 

Check the [vdiffr](https://github.com/r-lib/vdiffr) package for a guide on how to use visual regression testing.

**Comment by jamesotto852** [comment]
We have implemented many unit tests in #31, `covr::package_coverage()` now reports 95.05\% coverage.
