### ISSUE TITLE
Wrong legend when using probs in ascending order

### ISSUE THREAD

**Issue by z3tt** [jamesotto852/ggdensity#32]
Hi @jamesotto852, thanks for this wonderful package!

I just realized that the legend is wrong (labels are in reversed order) when passing custom probs. Simple example:

``` r
library(ggplot2)

## correct order with default probs
ggplot(mpg, aes(x = hwy, y = displ)) +
  ggdensity::geom_hdr_lines()
```

![](https://i.imgur.com/UL810J1.png)

``` r

## wrong order with modified probs
ggplot(mpg, aes(x = hwy, y = displ)) +
  ggdensity::geom_hdr_lines(probs = c(.25, .5, .75, .95))
```

![](https://i.imgur.com/yt1QWXf.png)

<sup>Created on 2023-11-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I am using package version 0.1.0 as it is available on CRAN currently.

**Comment by z3tt** [comment]
I just figured out that one can fix it by reversing the sequence of probabilities:

``` r
library(ggplot2)

## correct order with reversed probs
ggplot(mpg, aes(x = hwy, y = displ)) +
  ggdensity::geom_hdr_lines(probs = c(.95, .75, .5, .25))
```

![](https://i.imgur.com/swrZZyh.png)

<sup>Created on 2023-11-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I still think this issue should be targeted as one can easily get it wrong, by either only allowing sequences in descending order or fixing the mapping of alpha.

**Comment by jamesotto852** [comment]
Thanks for finding and reporting this! It looks like this was introduced when the logic from the various `StatHdr*()$compute_group()` functions converting from `get_hdr()` and `get_hdr_1d()` output to `data.frame` format was refactored with `res_to_df()` and `res_to_df_1d()` in fa2a7df -- we forgot to sort the probabilities in the helper functions. I've added the sorting and everything is now behaving as it should, this can be seen in the attached reprexes.

I've also added new visual tests to ensure the ordering of the probabilities doesn't impact the plots in the future.

``` r
library("ggdensity")
#> Loading required package: ggplot2

## correct order with reversed probs
ggplot(mpg, aes(x = hwy, y = displ)) +
  ggdensity::geom_hdr_lines(probs = c(.95, .75, .5, .25))
```

![](https://i.imgur.com/Zm0OOBL.png)

``` r

## wrong order with modified probs
ggplot(mpg, aes(x = hwy, y = displ)) +
  ggdensity::geom_hdr_lines(probs = c(.25, .5, .75, .95))
```

![](https://i.imgur.com/InfldkT.png)

``` r

## wrong order with modified probs, a different geom
ggplot(mpg, aes(x = hwy, y = displ)) +
  ggdensity::geom_hdr(probs = c(.25, .5, .75, .95))
```

![](https://i.imgur.com/SSvAp5i.png)

<sup>Created on 2023-11-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
